# Datasource configuration
spring:
  config:
    import: optional:secrets.yml
  datasource:
    url: jdbc:postgresql://localhost:54321/coinlift_db
    username: postgres
    password: password
  sql:
    init:
      mode: always

  # JPA, Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  # Maximum file size for multipart requests
  servlet:
    multipart:
      max-file-size: 10MB
      max-request_size: 10MB

  # Maximum size for in-memory data encoding/decoding
  codec:
    max-in-memory-size: 10MB

logging:
  pattern:
    #    console: "%highlight{[%-5level]} %cyan(%d{yyyy-MM-dd HH:mm:ss.SSS}) %yellow([%t]) %magenta(%logger{36}) - %msg%n"
    #    console: "%highlight{[%-5level]} %green(%d{yyyy-MM-dd HH:mm:ss.SSS}) %yellow([%t]) %cyan(%logger{36}) - %boldRed(%msg%n)"
    #    console: "%highlight{[%-5level]} %green(%d{yyyy-MM-dd HH:mm:ss.SSS}) %yellow([%t]) %cyan(%logger{36}) - %boldRed(%msg%n)"
    console: "%highlight{[%-5level]} %cyan(%d{yyyy-MM-dd HH:mm:ss.SSS}) %yellow([%t]) %magenta(%logger{36}) - %msg%n"
  level:
    org.springframework: info
    com.coinlift.backend: debug



# AWS data
aws:
  region: eu-west-2
  s3:
    buckets:
      customer: coinlift-test
