# Datasource configuration
spring:
  config:
    import: optional:secrets.yml
  datasource:
    url: jdbc:postgresql://localhost:54321/coinlift_db
    username: postgres
    password: password
  sql:
    init:
      mode: always

# JPA, Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

# Maximum file size for multipart requests
  servlet:
    multipart:
      max-file-size: 10MB
      max-request_size: 10MB

# Maximum size for in-memory data encoding/decoding
  codec:
    max-in-memory-size: 10MB

# AWS data
aws:
  region: eu-west-2
  s3:
    buckets:
      customer: coinlift-test
