# Datasource configuration
spring:
  config:
    import: secrets.yaml
  datasource:
    url: jdbc:postgresql://coin-lift-db.cwisjiyig4ci.eu-north-1.rds.amazonaws.com:5432/coinlift_db
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
